import 'game_models.dart';

class LevelsData {
  static List<LevelModel> getLevels() {
    return [
      // STAGE 01: Subnet Bypass
      LevelModel(
        id: 1,
        name: "Stage 01",
        codeName: "SUBNET_BYPASS",
        maxRam: 15,
        baseFirewallSpeed: 4.0,
        startCoords: const HexCoords(0, 0),
        portCoords: const HexCoords(2, 0),
        nodes: [
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.port, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.core, isRevealed: true, coreValue: 50),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.empty, isRevealed: true),
        ],
      ),

      // STAGE 02: Proxy Infiltration
      LevelModel(
        id: 2,
        name: "Stage 02",
        codeName: "PROXY_INFILTRATION",
        maxRam: 18,
        baseFirewallSpeed: 5.0,
        startCoords: const HexCoords(-1, 0),
        portCoords: const HexCoords(2, 1),
        nodes: [
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.core, isRevealed: true, coreValue: 75),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.port, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.core, isRevealed: true, coreValue: 75),
        ],
      ),

      // STAGE 03: Core Harvest
      LevelModel(
        id: 3,
        name: "Stage 03",
        codeName: "CORE_HARVEST",
        maxRam: 22,
        baseFirewallSpeed: 5.5,
        startCoords: const HexCoords(-2, 0),
        portCoords: const HexCoords(2, -1),
        dronePatrolPath: [
          const HexCoords(0, 0),
          const HexCoords(1, 0),
          const HexCoords(0, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.core, isRevealed: true, coreValue: 100),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.core, isRevealed: true, coreValue: 100),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.port, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
        ],
      ),

      // STAGE 04: Neural Cascade
      LevelModel(
        id: 4,
        name: "Stage 04",
        codeName: "NEURAL_CASCADE",
        maxRam: 25,
        baseFirewallSpeed: 6.0,
        startCoords: const HexCoords(-2, -1),
        portCoords: const HexCoords(2, 2),
        dronePatrolPath: [
          const HexCoords(-1, 1),
          const HexCoords(0, 1),
          const HexCoords(1, 1),
          const HexCoords(0, 2),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.core, isRevealed: true, coreValue: 125),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.core, isRevealed: true, coreValue: 125),
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.core, isRevealed: true, coreValue: 125),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 2), type: NodeType.port, isRevealed: true),
        ],
      ),

      // STAGE 05: Mainframe Core
      LevelModel(
        id: 5,
        name: "Stage 05",
        codeName: "MAINFRAME_CORE",
        maxRam: 28,
        baseFirewallSpeed: 6.5,
        startCoords: const HexCoords(0, -3),
        portCoords: const HexCoords(0, 3),
        dronePatrolPath: [
          const HexCoords(-1, 0),
          const HexCoords(0, 0),
          const HexCoords(1, 0),
          const HexCoords(0, 1),
          const HexCoords(-1, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(0, -3), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.core, isRevealed: true, coreValue: 150),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.core, isRevealed: true, coreValue: 150),
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.core, isRevealed: true, coreValue: 150),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.core, isRevealed: true, coreValue: 150),
          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 3), type: NodeType.port, isRevealed: true),
        ],
      ),

      // STAGE 06: Cyber Gateway
      LevelModel(
        id: 6,
        name: "Stage 06",
        codeName: "CYBER_GATEWAY",
        maxRam: 30,
        baseFirewallSpeed: 7.0,
        startCoords: const HexCoords(-3, 0),
        portCoords: const HexCoords(3, 0),
        dronePatrolPath: [
          const HexCoords(-1, 0),
          const HexCoords(0, -1),
          const HexCoords(1, -1),
          const HexCoords(1, 0),
          const HexCoords(0, 1),
          const HexCoords(-1, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(-3, 0), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(3, 0), type: NodeType.port, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.core, isRevealed: true, coreValue: 175),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.core, isRevealed: true, coreValue: 175),
          
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.core, isRevealed: true, coreValue: 175),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.core, isRevealed: true, coreValue: 175),
          
          NodeModel(coords: const HexCoords(-1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -2), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.empty, isRevealed: true),
        ],
      ),

      // STAGE 07: Quantum Firewall
      LevelModel(
        id: 7,
        name: "Stage 07",
        codeName: "QUANTUM_FIREWALL",
        maxRam: 34,
        baseFirewallSpeed: 7.5,
        startCoords: const HexCoords(0, -3),
        portCoords: const HexCoords(0, 3),
        dronePatrolPath: [
          const HexCoords(-2, 0),
          const HexCoords(-1, -1),
          const HexCoords(0, -1),
          const HexCoords(1, 0),
          const HexCoords(0, 1),
          const HexCoords(-1, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(0, -3), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -2), type: NodeType.core, isRevealed: true, coreValue: 200),
          NodeModel(coords: const HexCoords(1, -2), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.firewall, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.core, isRevealed: true, coreValue: 200),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.core, isRevealed: true, coreValue: 200),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.firewall, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.core, isRevealed: true, coreValue: 200),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(0, 3), type: NodeType.port, isRevealed: true),
        ],
      ),

      // STAGE 08: Black Hat Matrix
      LevelModel(
        id: 8,
        name: "Stage 08",
        codeName: "BLACK_HAT_MATRIX",
        maxRam: 38,
        baseFirewallSpeed: 8.0,
        startCoords: const HexCoords(-3, -1),
        portCoords: const HexCoords(3, 1),
        dronePatrolPath: [
          const HexCoords(-1, 0),
          const HexCoords(0, 0),
          const HexCoords(1, 0),
          const HexCoords(2, 0),
          const HexCoords(1, 1),
          const HexCoords(0, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(-3, -1), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.core, isRevealed: true, coreValue: 225),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.core, isRevealed: true, coreValue: 225),
          NodeModel(coords: const HexCoords(3, -1), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-3, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(3, 0), type: NodeType.firewall, isRevealed: true),

          NodeModel(coords: const HexCoords(-3, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.core, isRevealed: true, coreValue: 225),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.core, isRevealed: true, coreValue: 225),
          NodeModel(coords: const HexCoords(3, 1), type: NodeType.port, isRevealed: true),
        ],
      ),

      // STAGE 09: Deep Net Infiltrator
      LevelModel(
        id: 9,
        name: "Stage 09",
        codeName: "DEEP_NET_INFILTRATOR",
        maxRam: 42,
        baseFirewallSpeed: 8.5,
        startCoords: const HexCoords(0, -3),
        portCoords: const HexCoords(0, 3),
        dronePatrolPath: [
          const HexCoords(-1, -1),
          const HexCoords(0, -1),
          const HexCoords(1, 0),
          const HexCoords(1, 1),
          const HexCoords(0, 1),
          const HexCoords(-1, 0),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(0, -3), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -2), type: NodeType.core, isRevealed: true, coreValue: 250),
          NodeModel(coords: const HexCoords(1, -2), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.core, isRevealed: true, coreValue: 250),
          
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.core, isRevealed: true, coreValue: 250),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.firewall, isRevealed: true),
          
          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.core, isRevealed: true, coreValue: 250),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.core, isRevealed: true, coreValue: 250),
          
          NodeModel(coords: const HexCoords(0, 3), type: NodeType.port, isRevealed: true),
        ],
      ),

      // STAGE 10: The Root Overlord
      LevelModel(
        id: 10,
        name: "Stage 10",
        codeName: "THE_ROOT_OVERLORD",
        maxRam: 45,
        baseFirewallSpeed: 9.0,
        startCoords: const HexCoords(-3, 0),
        portCoords: const HexCoords(3, 0),
        dronePatrolPath: [
          const HexCoords(-2, 0),
          const HexCoords(-1, -1),
          const HexCoords(0, -1),
          const HexCoords(1, 0),
          const HexCoords(2, 0),
          const HexCoords(1, 1),
          const HexCoords(0, 1),
          const HexCoords(-1, 1),
        ],
        nodes: [
          NodeModel(coords: const HexCoords(-3, 0), type: NodeType.start, isRevealed: true, isHacked: true),
          NodeModel(coords: const HexCoords(-2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(-1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 0), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 0), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(3, 0), type: NodeType.port, isRevealed: true),

          NodeModel(coords: const HexCoords(-2, -1), type: NodeType.core, isRevealed: true, coreValue: 300),
          NodeModel(coords: const HexCoords(-1, -1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -1), type: NodeType.core, isRevealed: true, coreValue: 300),
          NodeModel(coords: const HexCoords(1, -1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(2, -1), type: NodeType.core, isRevealed: true, coreValue: 300),

          NodeModel(coords: const HexCoords(-2, 1), type: NodeType.core, isRevealed: true, coreValue: 300),
          NodeModel(coords: const HexCoords(-1, 1), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 1), type: NodeType.core, isRevealed: true, coreValue: 300),
          NodeModel(coords: const HexCoords(1, 1), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(2, 1), type: NodeType.core, isRevealed: true, coreValue: 300),

          NodeModel(coords: const HexCoords(-1, -2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, -2), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, -2), type: NodeType.empty, isRevealed: true),

          NodeModel(coords: const HexCoords(-1, 2), type: NodeType.empty, isRevealed: true),
          NodeModel(coords: const HexCoords(0, 2), type: NodeType.firewall, isRevealed: true),
          NodeModel(coords: const HexCoords(1, 2), type: NodeType.empty, isRevealed: true),
        ],
      ),
    ];
  }
}
